### ISSUE TITLE
parse title?

### ISSUE THREAD

**Issue by ralyodio** [Tsuk1ko/magnet2torrent-js#3]
Is it possible to writeout the title in `<title>.torrent`?

**Comment by Tsuk1ko** [comment]
Sure.

You can use [parse-torrent](https://www.npmjs.com/package/parse-torrent) to get title.

```javascript
const torrent = parseTorrent(buffer);
console.log(torrent.name);
```

**Comment by Tsuk1ko** [comment]
Maybe I can integrate it into API of magnet2torrent-js.

**Comment by Tsuk1ko** [comment]
I have published a new version, you can get its title easily now.

Please refer to the readme.
